#!/usr/bin/bash
#########################################################################
# Downloads Sentinel-1 files listed in sentinel1_data_links.txt.        #
#                                                                       #
# sentinel1_data_links.txt is generated by                              #
# search_and_download_sentinel1.py.  If this file does not exist        #
#                                                                       #
# Run: python search_and_download_sentinel1.py                          #
#                                                                       #
# Then run wget_for_sentinel1.sh                                        #
#                                                                       #
# This requires a .netrc file that contains Earthdata login credentials #
#########################################################################

INPUT_FILE='test.txt'
OUTDIR='./Data'

if [ ! -d $OUTDIR ]
then
    echo "$OUTDIR does not exist.  Creating it..."
    mkdir -p $OUTDIR
fi

wget -nd -P $OUTDIR -i $INPUT_FILE
